/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HeadRouteImport } from './routes/head'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuditorRouteImport } from './routes/auditor'
import { Route as ApproverRouteImport } from './routes/approver'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditorIndexRouteImport } from './routes/auditor.index'
import { Route as VendorRfqsRouteImport } from './routes/vendor.rfqs'
import { Route as VendorQuotationsRouteImport } from './routes/vendor.quotations'
import { Route as VendorProfileRouteImport } from './routes/vendor.profile'
import { Route as VendorOrdersRouteImport } from './routes/vendor.orders'
import { Route as VendorNotificationsRouteImport } from './routes/vendor.notifications'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard'
import { Route as SignupVendorRouteImport } from './routes/signup.vendor'
import { Route as SignupOrganizationRouteImport } from './routes/signup.organization'
import { Route as SignupMemberRouteImport } from './routes/signup.member'
import { Route as OfficerVendorsRouteImport } from './routes/officer.vendors'
import { Route as OfficerRfqsRouteImport } from './routes/officer.rfqs'
import { Route as OfficerNotificationsRouteImport } from './routes/officer.notifications'
import { Route as OfficerDashboardRouteImport } from './routes/officer.dashboard'
import { Route as HeadVerifyGstinRouteImport } from './routes/head.verify-gstin'
import { Route as HeadVendorsRouteImport } from './routes/head.vendors'
import { Route as HeadTeamRouteImport } from './routes/head.team'
import { Route as HeadSettingsRouteImport } from './routes/head.settings'
import { Route as HeadRfqsRouteImport } from './routes/head.rfqs'
import { Route as HeadEscalationsRouteImport } from './routes/head.escalations'
import { Route as HeadDashboardRouteImport } from './routes/head.dashboard'
import { Route as AuditorRfqTimelineRouteImport } from './routes/auditor.rfq-timeline'
import { Route as AuditorOverviewRouteImport } from './routes/auditor.overview'
import { Route as AuditorNotificationsRouteImport } from './routes/auditor.notifications'
import { Route as AuditorAuditLogsRouteImport } from './routes/auditor.audit-logs'
import { Route as AuditorAnomaliesRouteImport } from './routes/auditor.anomalies'
import { Route as ApproverPendingRouteImport } from './routes/approver.pending'
import { Route as ApproverNotificationsRouteImport } from './routes/approver.notifications'
import { Route as ApproverHistoryRouteImport } from './routes/approver.history'
import { Route as ApproverEscalationsRouteImport } from './routes/approver.escalations'
import { Route as ApproverDashboardRouteImport } from './routes/approver.dashboard'
import { Route as VendorRfqsIndexRouteImport } from './routes/vendor.rfqs.index'
import { Route as VendorOrdersIndexRouteImport } from './routes/vendor.orders.index'
import { Route as OfficerVendorsIndexRouteImport } from './routes/officer.vendors.index'
import { Route as OfficerRfqsIndexRouteImport } from './routes/officer.rfqs.index'
import { Route as VendorRfqsIdRouteImport } from './routes/vendor.rfqs.$id'
import { Route as VendorQuotationsIdRouteImport } from './routes/vendor.quotations.$id'
import { Route as VendorProfileCompleteRouteImport } from './routes/vendor.profile.complete'
import { Route as VendorOrdersIdRouteImport } from './routes/vendor.orders.$id'
import { Route as OfficerVendorsIdRouteImport } from './routes/officer.vendors.$id'
import { Route as OfficerRfqsCreateRouteImport } from './routes/officer.rfqs.create'
import { Route as OfficerRfqsIdRouteImport } from './routes/officer.rfqs.$id'
import { Route as HeadEscalationReviewRfqIdRouteImport } from './routes/head.escalation-review.$rfqId'
import { Route as ApproverCompareRfqIdRouteImport } from './routes/approver.compare.$rfqId'

const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadRoute = HeadRouteImport.update({
  id: '/head',
  path: '/head',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditorRoute = AuditorRouteImport.update({
  id: '/auditor',
  path: '/auditor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproverRoute = ApproverRouteImport.update({
  id: '/approver',
  path: '/approver',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditorIndexRoute = AuditorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuditorRoute,
} as any)
const VendorRfqsRoute = VendorRfqsRouteImport.update({
  id: '/rfqs',
  path: '/rfqs',
  getParentRoute: () => VendorRoute,
} as any)
const VendorQuotationsRoute = VendorQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProfileRoute = VendorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => VendorRoute,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => VendorRoute,
} as any)
const VendorNotificationsRoute = VendorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => VendorRoute,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => VendorRoute,
} as any)
const SignupVendorRoute = SignupVendorRouteImport.update({
  id: '/signup/vendor',
  path: '/signup/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupOrganizationRoute = SignupOrganizationRouteImport.update({
  id: '/signup/organization',
  path: '/signup/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupMemberRoute = SignupMemberRouteImport.update({
  id: '/signup/member',
  path: '/signup/member',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerVendorsRoute = OfficerVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerRfqsRoute = OfficerRfqsRouteImport.update({
  id: '/rfqs',
  path: '/rfqs',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerNotificationsRoute = OfficerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerDashboardRoute = OfficerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OfficerRoute,
} as any)
const HeadVerifyGstinRoute = HeadVerifyGstinRouteImport.update({
  id: '/verify-gstin',
  path: '/verify-gstin',
  getParentRoute: () => HeadRoute,
} as any)
const HeadVendorsRoute = HeadVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => HeadRoute,
} as any)
const HeadTeamRoute = HeadTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => HeadRoute,
} as any)
const HeadSettingsRoute = HeadSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HeadRoute,
} as any)
const HeadRfqsRoute = HeadRfqsRouteImport.update({
  id: '/rfqs',
  path: '/rfqs',
  getParentRoute: () => HeadRoute,
} as any)
const HeadEscalationsRoute = HeadEscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => HeadRoute,
} as any)
const HeadDashboardRoute = HeadDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HeadRoute,
} as any)
const AuditorRfqTimelineRoute = AuditorRfqTimelineRouteImport.update({
  id: '/rfq-timeline',
  path: '/rfq-timeline',
  getParentRoute: () => AuditorRoute,
} as any)
const AuditorOverviewRoute = AuditorOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuditorRoute,
} as any)
const AuditorNotificationsRoute = AuditorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuditorRoute,
} as any)
const AuditorAuditLogsRoute = AuditorAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuditorRoute,
} as any)
const AuditorAnomaliesRoute = AuditorAnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => AuditorRoute,
} as any)
const ApproverPendingRoute = ApproverPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => ApproverRoute,
} as any)
const ApproverNotificationsRoute = ApproverNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ApproverRoute,
} as any)
const ApproverHistoryRoute = ApproverHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ApproverRoute,
} as any)
const ApproverEscalationsRoute = ApproverEscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => ApproverRoute,
} as any)
const ApproverDashboardRoute = ApproverDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ApproverRoute,
} as any)
const VendorRfqsIndexRoute = VendorRfqsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRfqsRoute,
} as any)
const VendorOrdersIndexRoute = VendorOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorOrdersRoute,
} as any)
const OfficerVendorsIndexRoute = OfficerVendorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficerVendorsRoute,
} as any)
const OfficerRfqsIndexRoute = OfficerRfqsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficerRfqsRoute,
} as any)
const VendorRfqsIdRoute = VendorRfqsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VendorRfqsRoute,
} as any)
const VendorQuotationsIdRoute = VendorQuotationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VendorQuotationsRoute,
} as any)
const VendorProfileCompleteRoute = VendorProfileCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => VendorProfileRoute,
} as any)
const VendorOrdersIdRoute = VendorOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VendorOrdersRoute,
} as any)
const OfficerVendorsIdRoute = OfficerVendorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OfficerVendorsRoute,
} as any)
const OfficerRfqsCreateRoute = OfficerRfqsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => OfficerRfqsRoute,
} as any)
const OfficerRfqsIdRoute = OfficerRfqsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OfficerRfqsRoute,
} as any)
const HeadEscalationReviewRfqIdRoute =
  HeadEscalationReviewRfqIdRouteImport.update({
    id: '/escalation-review/$rfqId',
    path: '/escalation-review/$rfqId',
    getParentRoute: () => HeadRoute,
  } as any)
const ApproverCompareRfqIdRoute = ApproverCompareRfqIdRouteImport.update({
  id: '/compare/$rfqId',
  path: '/compare/$rfqId',
  getParentRoute: () => ApproverRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approver': typeof ApproverRouteWithChildren
  '/auditor': typeof AuditorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/head': typeof HeadRouteWithChildren
  '/login': typeof LoginRoute
  '/officer': typeof OfficerRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/vendor': typeof VendorRouteWithChildren
  '/approver/dashboard': typeof ApproverDashboardRoute
  '/approver/escalations': typeof ApproverEscalationsRoute
  '/approver/history': typeof ApproverHistoryRoute
  '/approver/notifications': typeof ApproverNotificationsRoute
  '/approver/pending': typeof ApproverPendingRoute
  '/auditor/anomalies': typeof AuditorAnomaliesRoute
  '/auditor/audit-logs': typeof AuditorAuditLogsRoute
  '/auditor/notifications': typeof AuditorNotificationsRoute
  '/auditor/overview': typeof AuditorOverviewRoute
  '/auditor/rfq-timeline': typeof AuditorRfqTimelineRoute
  '/head/dashboard': typeof HeadDashboardRoute
  '/head/escalations': typeof HeadEscalationsRoute
  '/head/rfqs': typeof HeadRfqsRoute
  '/head/settings': typeof HeadSettingsRoute
  '/head/team': typeof HeadTeamRoute
  '/head/vendors': typeof HeadVendorsRoute
  '/head/verify-gstin': typeof HeadVerifyGstinRoute
  '/officer/dashboard': typeof OfficerDashboardRoute
  '/officer/notifications': typeof OfficerNotificationsRoute
  '/officer/rfqs': typeof OfficerRfqsRouteWithChildren
  '/officer/vendors': typeof OfficerVendorsRouteWithChildren
  '/signup/member': typeof SignupMemberRoute
  '/signup/organization': typeof SignupOrganizationRoute
  '/signup/vendor': typeof SignupVendorRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/orders': typeof VendorOrdersRouteWithChildren
  '/vendor/profile': typeof VendorProfileRouteWithChildren
  '/vendor/quotations': typeof VendorQuotationsRouteWithChildren
  '/vendor/rfqs': typeof VendorRfqsRouteWithChildren
  '/auditor/': typeof AuditorIndexRoute
  '/approver/compare/$rfqId': typeof ApproverCompareRfqIdRoute
  '/head/escalation-review/$rfqId': typeof HeadEscalationReviewRfqIdRoute
  '/officer/rfqs/$id': typeof OfficerRfqsIdRoute
  '/officer/rfqs/create': typeof OfficerRfqsCreateRoute
  '/officer/vendors/$id': typeof OfficerVendorsIdRoute
  '/vendor/orders/$id': typeof VendorOrdersIdRoute
  '/vendor/profile/complete': typeof VendorProfileCompleteRoute
  '/vendor/quotations/$id': typeof VendorQuotationsIdRoute
  '/vendor/rfqs/$id': typeof VendorRfqsIdRoute
  '/officer/rfqs/': typeof OfficerRfqsIndexRoute
  '/officer/vendors/': typeof OfficerVendorsIndexRoute
  '/vendor/orders/': typeof VendorOrdersIndexRoute
  '/vendor/rfqs/': typeof VendorRfqsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approver': typeof ApproverRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/head': typeof HeadRouteWithChildren
  '/login': typeof LoginRoute
  '/officer': typeof OfficerRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/vendor': typeof VendorRouteWithChildren
  '/approver/dashboard': typeof ApproverDashboardRoute
  '/approver/escalations': typeof ApproverEscalationsRoute
  '/approver/history': typeof ApproverHistoryRoute
  '/approver/notifications': typeof ApproverNotificationsRoute
  '/approver/pending': typeof ApproverPendingRoute
  '/auditor/anomalies': typeof AuditorAnomaliesRoute
  '/auditor/audit-logs': typeof AuditorAuditLogsRoute
  '/auditor/notifications': typeof AuditorNotificationsRoute
  '/auditor/overview': typeof AuditorOverviewRoute
  '/auditor/rfq-timeline': typeof AuditorRfqTimelineRoute
  '/head/dashboard': typeof HeadDashboardRoute
  '/head/escalations': typeof HeadEscalationsRoute
  '/head/rfqs': typeof HeadRfqsRoute
  '/head/settings': typeof HeadSettingsRoute
  '/head/team': typeof HeadTeamRoute
  '/head/vendors': typeof HeadVendorsRoute
  '/head/verify-gstin': typeof HeadVerifyGstinRoute
  '/officer/dashboard': typeof OfficerDashboardRoute
  '/officer/notifications': typeof OfficerNotificationsRoute
  '/signup/member': typeof SignupMemberRoute
  '/signup/organization': typeof SignupOrganizationRoute
  '/signup/vendor': typeof SignupVendorRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/profile': typeof VendorProfileRouteWithChildren
  '/vendor/quotations': typeof VendorQuotationsRouteWithChildren
  '/auditor': typeof AuditorIndexRoute
  '/approver/compare/$rfqId': typeof ApproverCompareRfqIdRoute
  '/head/escalation-review/$rfqId': typeof HeadEscalationReviewRfqIdRoute
  '/officer/rfqs/$id': typeof OfficerRfqsIdRoute
  '/officer/rfqs/create': typeof OfficerRfqsCreateRoute
  '/officer/vendors/$id': typeof OfficerVendorsIdRoute
  '/vendor/orders/$id': typeof VendorOrdersIdRoute
  '/vendor/profile/complete': typeof VendorProfileCompleteRoute
  '/vendor/quotations/$id': typeof VendorQuotationsIdRoute
  '/vendor/rfqs/$id': typeof VendorRfqsIdRoute
  '/officer/rfqs': typeof OfficerRfqsIndexRoute
  '/officer/vendors': typeof OfficerVendorsIndexRoute
  '/vendor/orders': typeof VendorOrdersIndexRoute
  '/vendor/rfqs': typeof VendorRfqsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approver': typeof ApproverRouteWithChildren
  '/auditor': typeof AuditorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/head': typeof HeadRouteWithChildren
  '/login': typeof LoginRoute
  '/officer': typeof OfficerRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/vendor': typeof VendorRouteWithChildren
  '/approver/dashboard': typeof ApproverDashboardRoute
  '/approver/escalations': typeof ApproverEscalationsRoute
  '/approver/history': typeof ApproverHistoryRoute
  '/approver/notifications': typeof ApproverNotificationsRoute
  '/approver/pending': typeof ApproverPendingRoute
  '/auditor/anomalies': typeof AuditorAnomaliesRoute
  '/auditor/audit-logs': typeof AuditorAuditLogsRoute
  '/auditor/notifications': typeof AuditorNotificationsRoute
  '/auditor/overview': typeof AuditorOverviewRoute
  '/auditor/rfq-timeline': typeof AuditorRfqTimelineRoute
  '/head/dashboard': typeof HeadDashboardRoute
  '/head/escalations': typeof HeadEscalationsRoute
  '/head/rfqs': typeof HeadRfqsRoute
  '/head/settings': typeof HeadSettingsRoute
  '/head/team': typeof HeadTeamRoute
  '/head/vendors': typeof HeadVendorsRoute
  '/head/verify-gstin': typeof HeadVerifyGstinRoute
  '/officer/dashboard': typeof OfficerDashboardRoute
  '/officer/notifications': typeof OfficerNotificationsRoute
  '/officer/rfqs': typeof OfficerRfqsRouteWithChildren
  '/officer/vendors': typeof OfficerVendorsRouteWithChildren
  '/signup/member': typeof SignupMemberRoute
  '/signup/organization': typeof SignupOrganizationRoute
  '/signup/vendor': typeof SignupVendorRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/orders': typeof VendorOrdersRouteWithChildren
  '/vendor/profile': typeof VendorProfileRouteWithChildren
  '/vendor/quotations': typeof VendorQuotationsRouteWithChildren
  '/vendor/rfqs': typeof VendorRfqsRouteWithChildren
  '/auditor/': typeof AuditorIndexRoute
  '/approver/compare/$rfqId': typeof ApproverCompareRfqIdRoute
  '/head/escalation-review/$rfqId': typeof HeadEscalationReviewRfqIdRoute
  '/officer/rfqs/$id': typeof OfficerRfqsIdRoute
  '/officer/rfqs/create': typeof OfficerRfqsCreateRoute
  '/officer/vendors/$id': typeof OfficerVendorsIdRoute
  '/vendor/orders/$id': typeof VendorOrdersIdRoute
  '/vendor/profile/complete': typeof VendorProfileCompleteRoute
  '/vendor/quotations/$id': typeof VendorQuotationsIdRoute
  '/vendor/rfqs/$id': typeof VendorRfqsIdRoute
  '/officer/rfqs/': typeof OfficerRfqsIndexRoute
  '/officer/vendors/': typeof OfficerVendorsIndexRoute
  '/vendor/orders/': typeof VendorOrdersIndexRoute
  '/vendor/rfqs/': typeof VendorRfqsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approver'
    | '/auditor'
    | '/forgot-password'
    | '/head'
    | '/login'
    | '/officer'
    | '/reset-password'
    | '/vendor'
    | '/approver/dashboard'
    | '/approver/escalations'
    | '/approver/history'
    | '/approver/notifications'
    | '/approver/pending'
    | '/auditor/anomalies'
    | '/auditor/audit-logs'
    | '/auditor/notifications'
    | '/auditor/overview'
    | '/auditor/rfq-timeline'
    | '/head/dashboard'
    | '/head/escalations'
    | '/head/rfqs'
    | '/head/settings'
    | '/head/team'
    | '/head/vendors'
    | '/head/verify-gstin'
    | '/officer/dashboard'
    | '/officer/notifications'
    | '/officer/rfqs'
    | '/officer/vendors'
    | '/signup/member'
    | '/signup/organization'
    | '/signup/vendor'
    | '/vendor/dashboard'
    | '/vendor/notifications'
    | '/vendor/orders'
    | '/vendor/profile'
    | '/vendor/quotations'
    | '/vendor/rfqs'
    | '/auditor/'
    | '/approver/compare/$rfqId'
    | '/head/escalation-review/$rfqId'
    | '/officer/rfqs/$id'
    | '/officer/rfqs/create'
    | '/officer/vendors/$id'
    | '/vendor/orders/$id'
    | '/vendor/profile/complete'
    | '/vendor/quotations/$id'
    | '/vendor/rfqs/$id'
    | '/officer/rfqs/'
    | '/officer/vendors/'
    | '/vendor/orders/'
    | '/vendor/rfqs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approver'
    | '/forgot-password'
    | '/head'
    | '/login'
    | '/officer'
    | '/reset-password'
    | '/vendor'
    | '/approver/dashboard'
    | '/approver/escalations'
    | '/approver/history'
    | '/approver/notifications'
    | '/approver/pending'
    | '/auditor/anomalies'
    | '/auditor/audit-logs'
    | '/auditor/notifications'
    | '/auditor/overview'
    | '/auditor/rfq-timeline'
    | '/head/dashboard'
    | '/head/escalations'
    | '/head/rfqs'
    | '/head/settings'
    | '/head/team'
    | '/head/vendors'
    | '/head/verify-gstin'
    | '/officer/dashboard'
    | '/officer/notifications'
    | '/signup/member'
    | '/signup/organization'
    | '/signup/vendor'
    | '/vendor/dashboard'
    | '/vendor/notifications'
    | '/vendor/profile'
    | '/vendor/quotations'
    | '/auditor'
    | '/approver/compare/$rfqId'
    | '/head/escalation-review/$rfqId'
    | '/officer/rfqs/$id'
    | '/officer/rfqs/create'
    | '/officer/vendors/$id'
    | '/vendor/orders/$id'
    | '/vendor/profile/complete'
    | '/vendor/quotations/$id'
    | '/vendor/rfqs/$id'
    | '/officer/rfqs'
    | '/officer/vendors'
    | '/vendor/orders'
    | '/vendor/rfqs'
  id:
    | '__root__'
    | '/'
    | '/approver'
    | '/auditor'
    | '/forgot-password'
    | '/head'
    | '/login'
    | '/officer'
    | '/reset-password'
    | '/vendor'
    | '/approver/dashboard'
    | '/approver/escalations'
    | '/approver/history'
    | '/approver/notifications'
    | '/approver/pending'
    | '/auditor/anomalies'
    | '/auditor/audit-logs'
    | '/auditor/notifications'
    | '/auditor/overview'
    | '/auditor/rfq-timeline'
    | '/head/dashboard'
    | '/head/escalations'
    | '/head/rfqs'
    | '/head/settings'
    | '/head/team'
    | '/head/vendors'
    | '/head/verify-gstin'
    | '/officer/dashboard'
    | '/officer/notifications'
    | '/officer/rfqs'
    | '/officer/vendors'
    | '/signup/member'
    | '/signup/organization'
    | '/signup/vendor'
    | '/vendor/dashboard'
    | '/vendor/notifications'
    | '/vendor/orders'
    | '/vendor/profile'
    | '/vendor/quotations'
    | '/vendor/rfqs'
    | '/auditor/'
    | '/approver/compare/$rfqId'
    | '/head/escalation-review/$rfqId'
    | '/officer/rfqs/$id'
    | '/officer/rfqs/create'
    | '/officer/vendors/$id'
    | '/vendor/orders/$id'
    | '/vendor/profile/complete'
    | '/vendor/quotations/$id'
    | '/vendor/rfqs/$id'
    | '/officer/rfqs/'
    | '/officer/vendors/'
    | '/vendor/orders/'
    | '/vendor/rfqs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApproverRoute: typeof ApproverRouteWithChildren
  AuditorRoute: typeof AuditorRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HeadRoute: typeof HeadRouteWithChildren
  LoginRoute: typeof LoginRoute
  OfficerRoute: typeof OfficerRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  VendorRoute: typeof VendorRouteWithChildren
  SignupMemberRoute: typeof SignupMemberRoute
  SignupOrganizationRoute: typeof SignupOrganizationRoute
  SignupVendorRoute: typeof SignupVendorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/head': {
      id: '/head'
      path: '/head'
      fullPath: '/head'
      preLoaderRoute: typeof HeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditor': {
      id: '/auditor'
      path: '/auditor'
      fullPath: '/auditor'
      preLoaderRoute: typeof AuditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approver': {
      id: '/approver'
      path: '/approver'
      fullPath: '/approver'
      preLoaderRoute: typeof ApproverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditor/': {
      id: '/auditor/'
      path: '/'
      fullPath: '/auditor/'
      preLoaderRoute: typeof AuditorIndexRouteImport
      parentRoute: typeof AuditorRoute
    }
    '/vendor/rfqs': {
      id: '/vendor/rfqs'
      path: '/rfqs'
      fullPath: '/vendor/rfqs'
      preLoaderRoute: typeof VendorRfqsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/quotations': {
      id: '/vendor/quotations'
      path: '/quotations'
      fullPath: '/vendor/quotations'
      preLoaderRoute: typeof VendorQuotationsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/profile': {
      id: '/vendor/profile'
      path: '/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof VendorProfileRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/notifications': {
      id: '/vendor/notifications'
      path: '/notifications'
      fullPath: '/vendor/notifications'
      preLoaderRoute: typeof VendorNotificationsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof VendorRoute
    }
    '/signup/vendor': {
      id: '/signup/vendor'
      path: '/signup/vendor'
      fullPath: '/signup/vendor'
      preLoaderRoute: typeof SignupVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/organization': {
      id: '/signup/organization'
      path: '/signup/organization'
      fullPath: '/signup/organization'
      preLoaderRoute: typeof SignupOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/member': {
      id: '/signup/member'
      path: '/signup/member'
      fullPath: '/signup/member'
      preLoaderRoute: typeof SignupMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/vendors': {
      id: '/officer/vendors'
      path: '/vendors'
      fullPath: '/officer/vendors'
      preLoaderRoute: typeof OfficerVendorsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/rfqs': {
      id: '/officer/rfqs'
      path: '/rfqs'
      fullPath: '/officer/rfqs'
      preLoaderRoute: typeof OfficerRfqsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/notifications': {
      id: '/officer/notifications'
      path: '/notifications'
      fullPath: '/officer/notifications'
      preLoaderRoute: typeof OfficerNotificationsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/dashboard': {
      id: '/officer/dashboard'
      path: '/dashboard'
      fullPath: '/officer/dashboard'
      preLoaderRoute: typeof OfficerDashboardRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/head/verify-gstin': {
      id: '/head/verify-gstin'
      path: '/verify-gstin'
      fullPath: '/head/verify-gstin'
      preLoaderRoute: typeof HeadVerifyGstinRouteImport
      parentRoute: typeof HeadRoute
    }
    '/head/vendors': {
      id: '/head/vendors'
      path: '/vendors'
      fullPath: '/head/vendors'
      preLoaderRoute: typeof HeadVendorsRouteImport
      parentRoute: typeof HeadRoute
    }
    '/head/team': {
      id: '/head/team'
      path: '/team'
      fullPath: '/head/team'
      preLoaderRoute: typeof HeadTeamRouteImport
      parentRoute: typeof HeadRoute
    }
    '/head/settings': {
      id: '/head/settings'
      path: '/settings'
      fullPath: '/head/settings'
      preLoaderRoute: typeof HeadSettingsRouteImport
      parentRoute: typeof HeadRoute
    }
    '/head/rfqs': {
      id: '/head/rfqs'
      path: '/rfqs'
      fullPath: '/head/rfqs'
      preLoaderRoute: typeof HeadRfqsRouteImport
      parentRoute: typeof HeadRoute
    }
    '/head/escalations': {
      id: '/head/escalations'
      path: '/escalations'
      fullPath: '/head/escalations'
      preLoaderRoute: typeof HeadEscalationsRouteImport
      parentRoute: typeof HeadRoute
    }
    '/head/dashboard': {
      id: '/head/dashboard'
      path: '/dashboard'
      fullPath: '/head/dashboard'
      preLoaderRoute: typeof HeadDashboardRouteImport
      parentRoute: typeof HeadRoute
    }
    '/auditor/rfq-timeline': {
      id: '/auditor/rfq-timeline'
      path: '/rfq-timeline'
      fullPath: '/auditor/rfq-timeline'
      preLoaderRoute: typeof AuditorRfqTimelineRouteImport
      parentRoute: typeof AuditorRoute
    }
    '/auditor/overview': {
      id: '/auditor/overview'
      path: '/overview'
      fullPath: '/auditor/overview'
      preLoaderRoute: typeof AuditorOverviewRouteImport
      parentRoute: typeof AuditorRoute
    }
    '/auditor/notifications': {
      id: '/auditor/notifications'
      path: '/notifications'
      fullPath: '/auditor/notifications'
      preLoaderRoute: typeof AuditorNotificationsRouteImport
      parentRoute: typeof AuditorRoute
    }
    '/auditor/audit-logs': {
      id: '/auditor/audit-logs'
      path: '/audit-logs'
      fullPath: '/auditor/audit-logs'
      preLoaderRoute: typeof AuditorAuditLogsRouteImport
      parentRoute: typeof AuditorRoute
    }
    '/auditor/anomalies': {
      id: '/auditor/anomalies'
      path: '/anomalies'
      fullPath: '/auditor/anomalies'
      preLoaderRoute: typeof AuditorAnomaliesRouteImport
      parentRoute: typeof AuditorRoute
    }
    '/approver/pending': {
      id: '/approver/pending'
      path: '/pending'
      fullPath: '/approver/pending'
      preLoaderRoute: typeof ApproverPendingRouteImport
      parentRoute: typeof ApproverRoute
    }
    '/approver/notifications': {
      id: '/approver/notifications'
      path: '/notifications'
      fullPath: '/approver/notifications'
      preLoaderRoute: typeof ApproverNotificationsRouteImport
      parentRoute: typeof ApproverRoute
    }
    '/approver/history': {
      id: '/approver/history'
      path: '/history'
      fullPath: '/approver/history'
      preLoaderRoute: typeof ApproverHistoryRouteImport
      parentRoute: typeof ApproverRoute
    }
    '/approver/escalations': {
      id: '/approver/escalations'
      path: '/escalations'
      fullPath: '/approver/escalations'
      preLoaderRoute: typeof ApproverEscalationsRouteImport
      parentRoute: typeof ApproverRoute
    }
    '/approver/dashboard': {
      id: '/approver/dashboard'
      path: '/dashboard'
      fullPath: '/approver/dashboard'
      preLoaderRoute: typeof ApproverDashboardRouteImport
      parentRoute: typeof ApproverRoute
    }
    '/vendor/rfqs/': {
      id: '/vendor/rfqs/'
      path: '/'
      fullPath: '/vendor/rfqs/'
      preLoaderRoute: typeof VendorRfqsIndexRouteImport
      parentRoute: typeof VendorRfqsRoute
    }
    '/vendor/orders/': {
      id: '/vendor/orders/'
      path: '/'
      fullPath: '/vendor/orders/'
      preLoaderRoute: typeof VendorOrdersIndexRouteImport
      parentRoute: typeof VendorOrdersRoute
    }
    '/officer/vendors/': {
      id: '/officer/vendors/'
      path: '/'
      fullPath: '/officer/vendors/'
      preLoaderRoute: typeof OfficerVendorsIndexRouteImport
      parentRoute: typeof OfficerVendorsRoute
    }
    '/officer/rfqs/': {
      id: '/officer/rfqs/'
      path: '/'
      fullPath: '/officer/rfqs/'
      preLoaderRoute: typeof OfficerRfqsIndexRouteImport
      parentRoute: typeof OfficerRfqsRoute
    }
    '/vendor/rfqs/$id': {
      id: '/vendor/rfqs/$id'
      path: '/$id'
      fullPath: '/vendor/rfqs/$id'
      preLoaderRoute: typeof VendorRfqsIdRouteImport
      parentRoute: typeof VendorRfqsRoute
    }
    '/vendor/quotations/$id': {
      id: '/vendor/quotations/$id'
      path: '/$id'
      fullPath: '/vendor/quotations/$id'
      preLoaderRoute: typeof VendorQuotationsIdRouteImport
      parentRoute: typeof VendorQuotationsRoute
    }
    '/vendor/profile/complete': {
      id: '/vendor/profile/complete'
      path: '/complete'
      fullPath: '/vendor/profile/complete'
      preLoaderRoute: typeof VendorProfileCompleteRouteImport
      parentRoute: typeof VendorProfileRoute
    }
    '/vendor/orders/$id': {
      id: '/vendor/orders/$id'
      path: '/$id'
      fullPath: '/vendor/orders/$id'
      preLoaderRoute: typeof VendorOrdersIdRouteImport
      parentRoute: typeof VendorOrdersRoute
    }
    '/officer/vendors/$id': {
      id: '/officer/vendors/$id'
      path: '/$id'
      fullPath: '/officer/vendors/$id'
      preLoaderRoute: typeof OfficerVendorsIdRouteImport
      parentRoute: typeof OfficerVendorsRoute
    }
    '/officer/rfqs/create': {
      id: '/officer/rfqs/create'
      path: '/create'
      fullPath: '/officer/rfqs/create'
      preLoaderRoute: typeof OfficerRfqsCreateRouteImport
      parentRoute: typeof OfficerRfqsRoute
    }
    '/officer/rfqs/$id': {
      id: '/officer/rfqs/$id'
      path: '/$id'
      fullPath: '/officer/rfqs/$id'
      preLoaderRoute: typeof OfficerRfqsIdRouteImport
      parentRoute: typeof OfficerRfqsRoute
    }
    '/head/escalation-review/$rfqId': {
      id: '/head/escalation-review/$rfqId'
      path: '/escalation-review/$rfqId'
      fullPath: '/head/escalation-review/$rfqId'
      preLoaderRoute: typeof HeadEscalationReviewRfqIdRouteImport
      parentRoute: typeof HeadRoute
    }
    '/approver/compare/$rfqId': {
      id: '/approver/compare/$rfqId'
      path: '/compare/$rfqId'
      fullPath: '/approver/compare/$rfqId'
      preLoaderRoute: typeof ApproverCompareRfqIdRouteImport
      parentRoute: typeof ApproverRoute
    }
  }
}

interface ApproverRouteChildren {
  ApproverDashboardRoute: typeof ApproverDashboardRoute
  ApproverEscalationsRoute: typeof ApproverEscalationsRoute
  ApproverHistoryRoute: typeof ApproverHistoryRoute
  ApproverNotificationsRoute: typeof ApproverNotificationsRoute
  ApproverPendingRoute: typeof ApproverPendingRoute
  ApproverCompareRfqIdRoute: typeof ApproverCompareRfqIdRoute
}

const ApproverRouteChildren: ApproverRouteChildren = {
  ApproverDashboardRoute: ApproverDashboardRoute,
  ApproverEscalationsRoute: ApproverEscalationsRoute,
  ApproverHistoryRoute: ApproverHistoryRoute,
  ApproverNotificationsRoute: ApproverNotificationsRoute,
  ApproverPendingRoute: ApproverPendingRoute,
  ApproverCompareRfqIdRoute: ApproverCompareRfqIdRoute,
}

const ApproverRouteWithChildren = ApproverRoute._addFileChildren(
  ApproverRouteChildren,
)

interface AuditorRouteChildren {
  AuditorAnomaliesRoute: typeof AuditorAnomaliesRoute
  AuditorAuditLogsRoute: typeof AuditorAuditLogsRoute
  AuditorNotificationsRoute: typeof AuditorNotificationsRoute
  AuditorOverviewRoute: typeof AuditorOverviewRoute
  AuditorRfqTimelineRoute: typeof AuditorRfqTimelineRoute
  AuditorIndexRoute: typeof AuditorIndexRoute
}

const AuditorRouteChildren: AuditorRouteChildren = {
  AuditorAnomaliesRoute: AuditorAnomaliesRoute,
  AuditorAuditLogsRoute: AuditorAuditLogsRoute,
  AuditorNotificationsRoute: AuditorNotificationsRoute,
  AuditorOverviewRoute: AuditorOverviewRoute,
  AuditorRfqTimelineRoute: AuditorRfqTimelineRoute,
  AuditorIndexRoute: AuditorIndexRoute,
}

const AuditorRouteWithChildren =
  AuditorRoute._addFileChildren(AuditorRouteChildren)

interface HeadRouteChildren {
  HeadDashboardRoute: typeof HeadDashboardRoute
  HeadEscalationsRoute: typeof HeadEscalationsRoute
  HeadRfqsRoute: typeof HeadRfqsRoute
  HeadSettingsRoute: typeof HeadSettingsRoute
  HeadTeamRoute: typeof HeadTeamRoute
  HeadVendorsRoute: typeof HeadVendorsRoute
  HeadVerifyGstinRoute: typeof HeadVerifyGstinRoute
  HeadEscalationReviewRfqIdRoute: typeof HeadEscalationReviewRfqIdRoute
}

const HeadRouteChildren: HeadRouteChildren = {
  HeadDashboardRoute: HeadDashboardRoute,
  HeadEscalationsRoute: HeadEscalationsRoute,
  HeadRfqsRoute: HeadRfqsRoute,
  HeadSettingsRoute: HeadSettingsRoute,
  HeadTeamRoute: HeadTeamRoute,
  HeadVendorsRoute: HeadVendorsRoute,
  HeadVerifyGstinRoute: HeadVerifyGstinRoute,
  HeadEscalationReviewRfqIdRoute: HeadEscalationReviewRfqIdRoute,
}

const HeadRouteWithChildren = HeadRoute._addFileChildren(HeadRouteChildren)

interface OfficerRfqsRouteChildren {
  OfficerRfqsIdRoute: typeof OfficerRfqsIdRoute
  OfficerRfqsCreateRoute: typeof OfficerRfqsCreateRoute
  OfficerRfqsIndexRoute: typeof OfficerRfqsIndexRoute
}

const OfficerRfqsRouteChildren: OfficerRfqsRouteChildren = {
  OfficerRfqsIdRoute: OfficerRfqsIdRoute,
  OfficerRfqsCreateRoute: OfficerRfqsCreateRoute,
  OfficerRfqsIndexRoute: OfficerRfqsIndexRoute,
}

const OfficerRfqsRouteWithChildren = OfficerRfqsRoute._addFileChildren(
  OfficerRfqsRouteChildren,
)

interface OfficerVendorsRouteChildren {
  OfficerVendorsIdRoute: typeof OfficerVendorsIdRoute
  OfficerVendorsIndexRoute: typeof OfficerVendorsIndexRoute
}

const OfficerVendorsRouteChildren: OfficerVendorsRouteChildren = {
  OfficerVendorsIdRoute: OfficerVendorsIdRoute,
  OfficerVendorsIndexRoute: OfficerVendorsIndexRoute,
}

const OfficerVendorsRouteWithChildren = OfficerVendorsRoute._addFileChildren(
  OfficerVendorsRouteChildren,
)

interface OfficerRouteChildren {
  OfficerDashboardRoute: typeof OfficerDashboardRoute
  OfficerNotificationsRoute: typeof OfficerNotificationsRoute
  OfficerRfqsRoute: typeof OfficerRfqsRouteWithChildren
  OfficerVendorsRoute: typeof OfficerVendorsRouteWithChildren
}

const OfficerRouteChildren: OfficerRouteChildren = {
  OfficerDashboardRoute: OfficerDashboardRoute,
  OfficerNotificationsRoute: OfficerNotificationsRoute,
  OfficerRfqsRoute: OfficerRfqsRouteWithChildren,
  OfficerVendorsRoute: OfficerVendorsRouteWithChildren,
}

const OfficerRouteWithChildren =
  OfficerRoute._addFileChildren(OfficerRouteChildren)

interface VendorOrdersRouteChildren {
  VendorOrdersIdRoute: typeof VendorOrdersIdRoute
  VendorOrdersIndexRoute: typeof VendorOrdersIndexRoute
}

const VendorOrdersRouteChildren: VendorOrdersRouteChildren = {
  VendorOrdersIdRoute: VendorOrdersIdRoute,
  VendorOrdersIndexRoute: VendorOrdersIndexRoute,
}

const VendorOrdersRouteWithChildren = VendorOrdersRoute._addFileChildren(
  VendorOrdersRouteChildren,
)

interface VendorProfileRouteChildren {
  VendorProfileCompleteRoute: typeof VendorProfileCompleteRoute
}

const VendorProfileRouteChildren: VendorProfileRouteChildren = {
  VendorProfileCompleteRoute: VendorProfileCompleteRoute,
}

const VendorProfileRouteWithChildren = VendorProfileRoute._addFileChildren(
  VendorProfileRouteChildren,
)

interface VendorQuotationsRouteChildren {
  VendorQuotationsIdRoute: typeof VendorQuotationsIdRoute
}

const VendorQuotationsRouteChildren: VendorQuotationsRouteChildren = {
  VendorQuotationsIdRoute: VendorQuotationsIdRoute,
}

const VendorQuotationsRouteWithChildren =
  VendorQuotationsRoute._addFileChildren(VendorQuotationsRouteChildren)

interface VendorRfqsRouteChildren {
  VendorRfqsIdRoute: typeof VendorRfqsIdRoute
  VendorRfqsIndexRoute: typeof VendorRfqsIndexRoute
}

const VendorRfqsRouteChildren: VendorRfqsRouteChildren = {
  VendorRfqsIdRoute: VendorRfqsIdRoute,
  VendorRfqsIndexRoute: VendorRfqsIndexRoute,
}

const VendorRfqsRouteWithChildren = VendorRfqsRoute._addFileChildren(
  VendorRfqsRouteChildren,
)

interface VendorRouteChildren {
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorNotificationsRoute: typeof VendorNotificationsRoute
  VendorOrdersRoute: typeof VendorOrdersRouteWithChildren
  VendorProfileRoute: typeof VendorProfileRouteWithChildren
  VendorQuotationsRoute: typeof VendorQuotationsRouteWithChildren
  VendorRfqsRoute: typeof VendorRfqsRouteWithChildren
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorDashboardRoute: VendorDashboardRoute,
  VendorNotificationsRoute: VendorNotificationsRoute,
  VendorOrdersRoute: VendorOrdersRouteWithChildren,
  VendorProfileRoute: VendorProfileRouteWithChildren,
  VendorQuotationsRoute: VendorQuotationsRouteWithChildren,
  VendorRfqsRoute: VendorRfqsRouteWithChildren,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApproverRoute: ApproverRouteWithChildren,
  AuditorRoute: AuditorRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HeadRoute: HeadRouteWithChildren,
  LoginRoute: LoginRoute,
  OfficerRoute: OfficerRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  VendorRoute: VendorRouteWithChildren,
  SignupMemberRoute: SignupMemberRoute,
  SignupOrganizationRoute: SignupOrganizationRoute,
  SignupVendorRoute: SignupVendorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
